### PR TITLE
Use phin instead of Request

### PR DESCRIPTION
**Pull request by Ethanent**
[phin](https://github.com/Ethanent/phin) is a super lightweight HTTP client library. It has 0 dependencies! Using it in place of request reduces the dependency tree size by 22 packages, improving install time and general performance!

### CODE REVIEW

**Comment by zeke** [comment]
Thanks for the PR, @Ethanent 

FYI, I don't know much about this module. I just took it over when @azer unpublished his modules from npm as a political statement. 👊 

Are you sure this module still works? When I try to run the tests for your PR, I see `Error: Cannot find module 'ansi-codes'`. It looks like that module was never re-published to npm: https://www.npmjs.com/package/ansi-codes

**Comment by Ethanent** [comment]
@zeke Thanks for pointing that out. Seems to be an issue with the prova testing framework used in the package. I went ahead and switched the testing library to fix that issue.

The new testing library has 0 dependencies, reducing total tree size for dev dependencies by 303 packages to 1! Now testing actually works also. :)

**Comment by zeke** [comment]
Sounds good. Please take out the version bump change. I will bump the major when I do a release.

**Comment by Ethanent** [comment]
Ok, version for pull is 0.0.3.

**Comment by azer** [comment]
@Ethanent You can run the tests after setting the `prova` dependency point to `azer/prova` instead of `*` in the `package.json`

**Comment by zeke** [comment]
@Ethanent are you able to roll back your `whew` changes and point the prova dep at GitHub?

**Comment by Ethanent** [comment]
@zeke Consider it done. :)

Test returned to previous form. (Although the test API is down!) I restored prova as a dependency by referencing the GitHub repo at `azer/prova`.

**Comment by zeke** [comment]
I'm seeing an error running the tests locally:

```
    get last songs from radio paradise api
    
      getaddrinfo ENOTFOUND api.listenparadise.org api.listenparadise.org:80
      Error: getaddrinfo ENOTFOUND api.listenparadise.org api.listenparadise.org:80
          at errnoException (dns.js:50:10)
          at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)


/Users/z/git/zeke/get-json/test.js:8
    t.ok(body.ok);
             ^

TypeError: Cannot read property 'ok' of undefined
    at /Users/z/git/zeke/get-json/test.js:8:14
    at /Users/z/git/zeke/get-json/lib/node.js:8:6
    at ClientRequest.req.on (/Users/z/git/zeke/get-json/node_modules/phin/lib/phin.js:118:4)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
npm ERR! Test failed.  See above for more details.
```

I've enabled Travis CI on this repo. If you pull the latest changes, rebase your branch with master, and push up a fix, we'll see the test results here.

**Comment by Ethanent** [comment]
@zeke I committed a change to the test.js file. (The tests are currently broken in your master branch as the endpoint they connect to for testing isn't being hosted.)

I updated the endpoint to a domain being hosted actively (JSONTest API) but I'd recommend in the future hosting a local server within test.js for offline testing!

**Comment by zeke** [comment]
```
~/git/zeke/get-json master
$ np major
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 get-json 1.0.0 published 🎉
```

**Pull request merged**
